### ISSUE TITLE
pybullet needs setLinearFactor/setAngularFactor to lock axis

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#1028]
We will need this to replicate the 2D RL environments such as humanoid/half-cheetah. I believe it is not yet available. Maybe I will start an attempt to add it. Or is there another trick to achieve this for now?

**Comment by erwincoumans** [comment]
Please see the MJCF files, it loads the original MuJoCo environments. 2D works automatically, since it fixes the base and adds single DOFs at a time. Try running Bullet ExampleBrowser / Importers / ImportMJCF a few times and watch the various mjcf files. By default the joints are locked (motors with target 0) just use pybullet.loadMJCF and set the motors as desired.
