### ISSUE TITLE
btMultiSphereShape proper scaling (was googlecode Issue 636)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#125]
See https://code.google.com/p/bullet/issues/detail?id=636&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by MiCroN3000** [comment]
Hi, I was wondering if the given solution could be added to the Bullet source code? 
Also is it really needed to introduce a backwards compatibility flag for this issue? It seems to me that this just solves a bug that shouldn't be, and that the solution is pretty local. If the solution can have other side effects, than I wonder what they could be..

**Comment by benelot** [comment]
Hi,
You could create a pull request referencing this issue to propose the
implementation of it.

**Comment by MiCroN3000** [comment]
Hi, I'm trying to push a branch that contains this fix so i can create a pull request for it. But I'm getting a 403, permission denied, for good reason I guess as I am not a contributor to this project. Can you help me with this? I would love to contribute here. 

On a different note, I have also been working on (more like hacking) the kinematic character controller of Bullet. I don't know of it is interesting enough to contribute that one already, but I do intend to rewrite the thing completely, not sure when I'll find the time but I intend to make that happen at some point :)

**Comment by benelot** [comment]
Hi,

I am happy you created the fix for it. The problem why you get the 403 is
that you try to push to the original repository. What you have to do
instead is to fork the repository, then apply your changes in a branch as
you did and then push this branch to your forked repository. Then you can
click the create pull request on your forked repository to publish the
content of the branch to the bulletphysics/bullet3 repo.

About your changes of the kinematic character controller: You can easily
put them into another branch and create a pull request for it, as long as
your code is clean and you can explain your changes reasonably, you can
definitely discuss them with Erwin Coumans (owner of bullet physics repo).
Also, the pull requested branch is not final at this point. On github, it
can then be discussed on the page and everything you commit to the branch
afterwards will be automatically included in the pull request.

**Comment by erwincoumans** [comment]
Patch is in this pull request, will be applied asap:
https://github.com/bulletphysics/bullet3/pull/680
Thanks a lot for the reminder!

**Comment by MiCroN3000** [comment]
No problem, thanks for patching it and thanks for the explanation, I'll try to get the character controller in a pull request.

**Comment by benelot** [comment]
Did you succeed in making a branch for pull requesting? Otherwise, send me
the changed files and I will merge them in.

**Comment by MiCroN3000** [comment]
Sorry for the late response (in the middle of a move). I created the pull request for the character controller, hope it's ok. I've been sitting on this for quite a while now and am still a bit reluctant to push the code, because it feels like I'm building hacks on hacks that were already present in the controller. It is not very clean code, and I guess I kindof beat it into submission, so it fits my needs better. I still intend to rewrite the entire controller, but I'm not sure when I'll get around to it, it might take a while. Anyway, I explained my intend of the controller in the pull request, hope it helps.
