### ISSUE TITLE
Implement CPU multithreaded version (pthreads/TBB/OpenCL/MPI etc)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#126]
Right now Bullet 2 is single threaded and we discarded the obsolete BulletMultiThreaded. Bullet 3 OpenCL is mainly designed for GPU and OpenCL drivers are unreliable. It would be good to create a new multithreaded version of Bullet keeping in mind Bullet 2 and Bullet 3 OpenCL.

**Comment by erwincoumans** [comment]
This was contributed now, CPU multithreading can be enabled. See Bullet/examples/BenchmarkDemo for an example. Thanks @lunkhound !

**Comment by georgwuensch** [comment]
Dear Erwin, Dear Lunkhound, great that this is finally integrated. Thank you!

One question from your experience, what differences do you see between using openMP, ThreadSupport and TBB? Will there be any differences? 

I am working on a little logger to do more testing on different laptops and workstations with the different options. 

Maybe I can share some results on this if you like.

Yours Georg.

**Comment by georgwuensch** [comment]
HI, While looking into it I found (I am still compiling with Studio 2010...) that it uses concurrency:: as namespace for the ms ppl, while it only compiles with Concurrency:: AM I missing a settings there?

**Comment by erwincoumans** [comment]
You may have to fix things to get it the various multi-threading working.

**Comment by lunkhound** [comment]
Hi,

The PPL option should compile for MSVC 2013 and 2015 as I recall. I never tried it with VC 2010, so it sounds like it only works with newer versions of PPL. I don't really recommend using PPL. Its mainly there as an example of how to implement a task scheduler for Bullet. Performance wasn't great compared to the other options.

The ThreadSupport option is probably the best choice for most cases. It's built-in (to Bullet) so there's no extra setup, and it has the best performance (on the Windows platform at least, according to my testing).

I found IntelTBB to also have good performance, but it's a bit of a hassle to setup since it's an external library.

OpenMP on windows with MSVC works, and is very easy to setup since it is built into the compiler but doesn't perform that great. With other compilers hopefully the performance is better.

Please feel free to share your results with CPU multithreading on this [Forum thread](https://pybullet.org/Bullet/phpBB3/viewtopic.php?f=9&t=10232)
