### ISSUE TITLE
Bullet 2.87 changelog

### ISSUE THREAD

**Issue by Krakean** [bulletphysics/bullet3#1541]
Hello
Where I can find summarized(not detailed like on github) changelog of whats new/changes/fixed in 2.87 version?

**Comment by Krakean** [comment]
@erwincoumans any advice? or there is no more changelogs for bullets, only github commits history?

**Comment by erwincoumans** [comment]
Yes, only commit logs.

On Feb 6, 2018 2:10 PM, "Dmitry Koteroff" <notifications@github.com> wrote:

@erwincoumans <https://github.com/erwincoumans> any advice? or there is no
more changelogs for bullets, only github commits history?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bulletphysics/bullet3/issues/1541#issuecomment-363581942>,
or mute the thread
