### ISSUE TITLE
App_Bullet3_OpenCL_Demos Segmentation fault

### ISSUE THREAD

**Issue by sabotage3d** [bulletphysics/bullet3#200]
Hello ,

I am getting segmentation fault when I try the OpenCL Demos from this git commit: e317b646430e8601ffa0cdddf3dfd77a56a200c7

This is my log:

    main startCreating context
    Created GL 3.0 context
    Direct GLX rendering context obtained
    Making context current
    GL_VENDOR=NVIDIA Corporation
    GL_RENDERER=Quadro K4000/PCIe/SSE2
    GL_VERSION=3.2.0 NVIDIA 319.60
    GL_SHADING_LANGUAGE_VERSION=1.50 NVIDIA via Cg compiler
    pthread_getconcurrency()=0
    -----------------------------------------------------
    Segmentation fault

**Comment by Flix01** [comment]
Just wanted to report that on Unbuntu 64bit 15.04, I experienced the same issue:

>  > ./App_Bullet3*
main startCreating context
Created GL 3.0 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce GT 630/PCIe/SSE2
GL_VERSION=3.2.0 NVIDIA 346.59
GL_SHADING_LANGUAGE_VERSION=1.50 NVIDIA via Cg compiler
pthread_getconcurrency()=0
App_Bullet3_OpenCL_Demos_clew_gmake_x64_release: ../../btgui/OpenGLWindow/LoadShader.cpp:21: GLuint gltLoadShaderPair(const char*, const char*): Assertion `glGetError()==0' failed.
started GwenUserInterfaceAborted

I just want to report this (because I'm just interested in Bullet2 actually...).

However : <b>Test_OpenCL_Bullet3_gmake_x64_release, Test_OpenCL_primitives, etc.</b> all run correctly, and even <b>Test_Gwen_OpenGL_gmake_x64_release</b> works, even if I got a strange output when I close the window:

> 	visual 0x24 selected
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce GT 630/PCIe/SSE2
GL_VERSION=4.5.0 NVIDIA 346.59
GL_SHADING_LANGUAGE_VERSION=4.50 NVIDIA
pthread_getconcurrency()=0
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 5557 requests (5557 known processed) with 0 events remaining.

**Comment by erwincoumans** [comment]
The demos are all refactored into 'examples/ExampleBrowser', and this sets 'glewExperimental=true;'
Can you please give the latest revision at http://github.com/bulletphysics/bullet3 a try and report back?

**Comment by erwincoumans** [comment]
By the way, I disabled OpenCL support in the ExampleBrowser by default, but you can enable it using a command-line flag: App_ExampleBrowser_gmake --enable_experimental_opencl
I fixed another NVIDIA/OpenCL issue, one kernal was reading an array out-of-bounds.

**Comment by Flix01** [comment]
Yes, the <b>ExampleBrowser</b> works (I've just tested the bullet3-2.83 release package).

But now I can't find <b>App_Bullet3_OpenCL_Demos_clew_gmake_x64_release</b> anymore.
The demos inside "ExampleBrowser" all seem to be related to Bullet2, isn't it ?
So now the bullet3(=GPU support) demos are limited to the  --enable_experimental_opencl command line flag (i.e Box-Box and Pair Bench). Is that correct ?

**Comment by erwincoumans** [comment]
I likely re-enable other OpenCL demos too. I just wanted to get 'some' 2.83 release tagged, and cleaned up some mess into a single Example Browser.

If you want, you can try to enable a few other OpenCL demos. In fact, it should be almost trivial to enable a few more demos in the examples/OpenCL/rigidbody/GpuConvexScene.cpp file (next to box-box). The other files in examples/OpenCL/rigidbody/ need a bit more conversion work, not too complex.

Thanks!

**Comment by erwincoumans** [comment]
If you use the premake build system (bullet/build2) then the example browser has a command-line flag --enable_experimental_opencl that let's you experiment with a few OpenCL examples. This is not enabled in CMake, just in premake. Not all OpenCL examples have been ported (yet). Let's close this for now. If you have time and enable some more OpenCL examples in the example browser, please create a new pull request and use premake.
