### ISSUE TITLE
Pybullet not recognizing hollowed part of hollowed cylinder OBJ file

### ISSUE THREAD

**Issue by aznshodan** [bulletphysics/bullet3#2347]
I am using a hollowed cylinder OBJ file but as you can see below, pybullet doesn't seem to recognize the hollowed part. I attached the blender file, obj files. Any suggestions would be much appreciated.

![problem](https://user-images.githubusercontent.com/7860026/62275107-36368d80-b47c-11e9-8c77-1906d1912b05.png)

[hollowed_cylinder.zip](https://github.com/bulletphysics/bullet3/files/3455517/hollowed_cylinder.zip)

**Comment by erwincoumans** [comment]
Do you want the cylinder to be dynamic moving or static environment?
For dynamic moving, you can consider using convex decomposition, using V-HACFD. There is a utility to do this in the Extras folder, use premake.
For static geometry, you can flag the obj mesh as concave: modify the URDF file and in the collision tag add 
~~~~~~~~~~~~~
<collision concave="yes">
~~~~~~~~~~~~~
Only do this when needed, otherwise it hurts performance and stability.

**Comment by aznshodan** [comment]
I see. Thank you for the quick response!
