### ISSUE TITLE
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

### ISSUE THREAD

**Issue by richardrl** [bulletphysics/bullet3#2503]
`  p.startStateLogging(p.STATE_LOGGING_VIDEO_MP4, "test.mp4")

`

I assume, in the above "startStateLogging" function, it uses the getCameraImage function. How do I change the width in "startStateLogging" ? I can't find the function definition anywhere in this repo.

**Comment by erwincoumans** [comment]
This function relies on ffmpeg installed and working properly. See the settings here:
https://github.com/bulletphysics/bullet3/blob/master/examples/OpenGLWindow/SimpleOpenGL3App.cpp#L1093

Instead of this, you can use getCameraImage and create a video in Python (OpenAI Gym does this), or write images to disk and create a video manually.
