### ISSUE TITLE
Is it possible to load a mesh file as an geometry?

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2617]
Hello.
I'd like to use a mesh file as geometry in the physics engine.
For example, I have a scanned mesh file of stairs, and I want to control my robot on such terrain. 

I'm aware pybullet can load URDF, SDF and XML. But are there any easy ways to convert scanned mesh (e.g., obj or ply file) into a file format which is compatible with pybullet?

Thanks in advance.

**Comment by erwincoumans** [comment]
URDF files contain visual and collision elements already, and they can be meshes.
By default, PyBullet uses the convex hull of mesh elements, for collision.
For concave environments you can use the 'use
See this example:
https://github.com/bulletphysics/bullet3/blob/master/data/samurai.urdf
~~~~~~~~~~~~~~~~~~~
<?xml version="1.0" ?>
<robot name="cube.urdf">
  <link concave="yes" name="baseLink">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
       <mass value=".0"/>
       <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <visual>
      <origin rpy="1.5707963 0 0" xyz="0 0 0"/>
      <geometry>
				<mesh filename="samurai_monastry.obj" scale="1 1 1"/>
      </geometry>
       <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision concave="yes">
      <origin rpy="1.5707963 0 0" xyz="0 0 0"/>
     <geometry>
				<mesh filename="samurai_monastry.obj" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
</robot>

~~~~~~~~~~~~~~~~~~~
So you use the 'concave=yes' in the collision tag.

Alternatively, instead of using URDF that points to a obj file, you can programmatically create a mesh from an obj file, and mark it as concave.

See this example:
https://github.com/bulletphysics/bullet3/blob/aec9968e281faca7bc56bc05ccaf0ef29d82d062/examples/pybullet/examples/internalEdge.py
