### ISSUE TITLE
How to make a soft body file (.obj or .vtk) for loading in pybullet ?

### ISSUE THREAD

**Issue by deepakraina99** [bulletphysics/bullet3#3091]
I saw some examples where .obj and .vtk files are used for soft bodies. How these files are designed. I used to get .obj and .dae files from standard designing software but those are for rigid bodies. Loading those files (.obj) using p.loadSoftBody gives no effect as a soft body. Can someone guide me regarding this?

Thanks.

**Comment by yangdeai** [comment]
I also want to know this too, please!! I want to simulate catheter,blood vessel and so on. Of course, I still need to simulate a robot to control the catheter into the blood vessel pointing position!

**Comment by HenningLuo** [comment]
I do not think loading objects in obj format is a good choice, since it only specifies the surface polygons of the object. Unless this is fabric or cloth, objects with volume should collapse when loaded in FEM mode. The vtk files in bullet examples are all generated with gmsh, so maybe that is the right software for modelling soft objects. I am only getting started to build these model as well, please forgive me if I am wrong.

**Comment by seann999** [comment]
Bump; I'm trying to use some software called gmsh but I have no idea what I'm doing

**Comment by deepakraina99** [comment]
> Bump; I'm trying to use some software called gmsh but I have no idea what I'm doing

Yes, I am also at the same stage. Pybullet should put up some documentation with respect to the modeling of soft bodies.

**Comment by erwincoumans** [comment]
see https://github.com/bulletphysics/bullet3/issues/2726
