### ISSUE TITLE
Why does bullet support both premake and CMake?

### ISSUE THREAD

**Issue by cirosantilli** [bulletphysics/bullet3#600]
The readme says that:

> Build instructions for Bullet using premake. You can also use cmake instead.

Is there one which is deprecated / preferred? Why have two build systems?

**Comment by erwincoumans** [comment]
cmake is more widely used, so it is useful to have, but I prefer premake for various reasons, so I maintain that as well: premake has a nicer scripting language for custom build steps, the premake generated IDE projects are better organized, and the premake generated Makefile is not dependent on anything (unlike cmake generated files, which still require cmake). That's why both.
